/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.epm.acmi.struts.form;

import java.util.TreeMap;

import org.apache.struts.action.ActionForm;


import com.cc.framework.adapter.struts.FormActionContext;

/** 
 * MyEclipse Struts
 * Creation date: 04-03-2008
 * 
 * XDoclet definition:
 * @struts.form name="amendmentMainForm"
 */
public class AmendmentMainForm extends ActionForm {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String policyid;
	private String name;
	private String wrong_app;
	private String description;
	private String amendmentTextArea;
	
	public TreeMap getWrongAppOptions()
	{
		
		TreeMap status = new TreeMap();
		
		status.put(" ", " ");
		status.put("0", "Proxy");
		status.put("1", "Trust");
		return status;
	}
	
	
	public String getPolicyid() {
		return policyid;
	}
	public void setPolicyid(String policyid) {
		this.policyid = policyid;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public String getWrong_app() {
		return wrong_app;
	}
	public void setWrong_app(String wrong_app) {
		this.wrong_app = wrong_app;
	}
	public String getDescription() {
		return description;
	}
	public void setDescription(String description) {
		this.description = description;
	}
	public String getAmendmentTextArea() {
		return amendmentTextArea;
	}
	public void setAmendmentTextArea(String amendmentTextArea) {
		this.amendmentTextArea = amendmentTextArea;
	}
	
	public AmendmentMainForm() {
		super();
		// TODO Auto-generated constructor stub
	}
	public void validateForm(FormActionContext ctx) 
	{
		//FieldCheckCustom.validateRequired(this.getAmendmentTextArea(), ctx, "Amendment Text");
		
	}
	
	public void clear() 
	{
		this.setAmendmentTextArea("");
		this.setDescription("");
		this.setName("");
		this.setPolicyid("");
		this.setWrong_app("");
	
	}

	public void save() 
	{
		this.setAmendmentTextArea(getAmendmentTextArea());
		this.setDescription(getDescription());
		this.setName(getName());
		this.setPolicyid(getPolicyid());
		this.setWrong_app(getWrong_app());
	}
	
}