/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.epm.acmi.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 03-27-2008
 * 
 * XDoclet definition:
 * @struts.form name="browsePoliciesForm"
 */
public class BrowsePoliciesForm extends ActionForm {
	/*
	 * Generated Methods
	 */
	
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private String KEY_INSURED_SEARCH_NAME;
	private String POLICY_ID;
	private String KEY_PRODUCT_ID;
	private String KEY_INSURED_PERSON_ID;

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}



	public String getKEY_PRODUCT_ID() {
		return KEY_PRODUCT_ID;
	}

	public void setKEY_PRODUCT_ID(String key_product_id) {
		KEY_PRODUCT_ID = key_product_id;
	}

	public String getKEY_INSURED_PERSON_ID() {
		return KEY_INSURED_PERSON_ID;
	}

	public void setKEY_INSURED_PERSON_ID(String key_insured_person_id) {
		KEY_INSURED_PERSON_ID = key_insured_person_id;
	}



	public String getKEY_INSURED_SEARCH_NAME() {
		return KEY_INSURED_SEARCH_NAME;
	}



	public void setKEY_INSURED_SEARCH_NAME(String key_insured_search_name) {
		KEY_INSURED_SEARCH_NAME = key_insured_search_name;
	}



	public String getPOLICY_ID() {
		return POLICY_ID;
	}



	public void setPOLICY_ID(String policy_id) {
		POLICY_ID = policy_id;
	}


	public void clear()
	{
		this.setKEY_INSURED_SEARCH_NAME("");
		
	}

	
}