/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.epm.acmi.struts.form;

import org.apache.struts.action.ActionForm;

/** 
 * MyEclipse Struts
 * Creation date: 04-01-2008
 * 
 * XDoclet definition:
 * @struts.form name="browsePolicyCertPersonForm"
 */
public class BrowsePolicyCertPersonForm extends ActionForm {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private String POLICY_ID ="";
	private String PERSON_ID ="";
	private String PERSON_SEARCH_NAME1  ="";
	
	public String getPOLICY_ID() {
		return POLICY_ID;
	}
	public void setPOLICY_ID(String policy_id) {
		POLICY_ID = policy_id;
	}
	public String getPERSON_ID() {
		return PERSON_ID;
	}
	public void setPERSON_ID(String person_id) {
		PERSON_ID = person_id;
	}
	public String getPERSON_SEARCH_NAME1() {
		return PERSON_SEARCH_NAME1;
	}
	public void setPERSON_SEARCH_NAME1(String person_search_name1) {
		PERSON_SEARCH_NAME1 = person_search_name1;
	}

	
}