/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.epm.acmi.struts.form;

import java.util.TreeMap;

import org.apache.struts.action.ActionForm;

import com.cc.framework.adapter.struts.FormActionContext;

/** 
 * MyEclipse Struts
 * Creation date: 04-01-2008
 * 
 * XDoclet definition:
 * @struts.form name="eventStdMemoForm"
 */
public class EventStdMemoForm extends ActionForm {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	
	private String policyno;
	private String event_id;
	private String std_event;
	private String description;
	private String attachment;
	private String recipient_id;
	private String recipient_name;
	private String memoid;
	private String status;
	private String requested;
	private String respn_date;
	private String second_request;
	private String application_formid;
	private String freeformind;
	private String stdletterTextArea;
	

	public EventStdMemoForm() {
		super();
	}

	public TreeMap getStatusOptions()
	{
		
		TreeMap status = new TreeMap();
			
		/*-- -------------------------------------------------- ---
		I  INCOMPLETE (NO INFORMATION)                         Y 
		O  ORDERED                                             N 
		P  PENDING                                             N 
		R  RECEIVED                                            Y 
		V  VOID                                                Y 
		W  WAIVED/WITHDRAWN                                    Y */
		
		status.put(" ", " ");
		status.put("I", "I: INCOMPLETE (NO INFORMATION)");
		status.put("O", "O: ORDERED");
		status.put("P", "P: PENDING");
		status.put("R", "R: RECEIVED");
		status.put("V", "V: VOID");
		status.put("W", "W: WAIVED/WITHDRAWN");
		
		return status;
		
	}

	public TreeMap getSecondRequestOptions()
	{
		
		TreeMap secondrequest = new TreeMap();
		
		secondrequest.put(" ", " ");
		secondrequest.put("Y", "Yes");
		secondrequest.put("N", "No");
		
		return secondrequest;
		
	}
	
	public TreeMap getFreeformIndOptions()
	{
		
		TreeMap freeform = new TreeMap();
		
		freeform.put(" ", " ");
		freeform.put("Y", "Yes");
		freeform.put("N", "No");
		
		return freeform;
		
	}
	
	public String getEvent_id() {
		return event_id;
	}

	public void setEvent_id(String event_id) {
		this.event_id = event_id;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getStd_event() {
		return std_event;
	}

	public void setStd_event(String std_event) {
		this.std_event = std_event;
	}

	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getRequested() {
		return requested;
	}

	public void setRequested(String requested) {
		this.requested = requested;
	}

	public String getRecipient_id() {
		return recipient_id;
	}

	public void setRecipient_id(String recipient_id) {
		this.recipient_id = recipient_id;
	}



	public String getRecipient_name() {
		return recipient_name;
	}



	public void setRecipient_name(String recipient_name) {
		this.recipient_name = recipient_name;
	}



	public String getSecond_request() {
		return second_request;
	}



	public void setSecond_request(String second_request) {
		this.second_request = second_request;
	}



	public String getMemoid() {
		return memoid;
	}



	public void setMemoid(String memoid) {
		this.memoid = memoid;
	}



	public String getPolicyno() {
		return policyno;
	}



	public void setPolicyno(String policyno) {
		this.policyno = policyno;
	}



	public String getAttachment() {
		return attachment;
	}



	public void setAttachment(String attachment) {
		this.attachment = attachment;
	}



	public String getRespn_date() {
		return respn_date;
	}



	public void setRespn_date(String respn_date) {
		this.respn_date = respn_date;
	}



	public String getApplication_formid() {
		return application_formid;
	}



	public void setApplication_formid(String application_formid) {
		this.application_formid = application_formid;
	}



	public String getFreeformind() {
		return freeformind;
	}



	public void setFreeformind(String freeformind) {
		this.freeformind = freeformind;
	}



	public String getStdletterTextArea() {
		return stdletterTextArea;
	}



	public void setStdletterTextArea(String stdletterTextArea) {
		this.stdletterTextArea = stdletterTextArea;
	}

	
	public void clear()
	{
		this.setPolicyno("");
		this.setEvent_id("");
		this.setStd_event("");
		this.setDescription("");
		this.setAttachment("");
		this.setRecipient_id("");
		this.setRecipient_name("");
		this.setMemoid("");
		this.setStatus("");
		this.setRequested("");
		this.setRespn_date("");
		this.setSecond_request("");
		this.setApplication_formid("");
		this.setFreeformind("");
		this.setStdletterTextArea("");
	}



	public void save() 
	{
		
		this.setPolicyno(getPolicyno());
		this.setEvent_id(getEvent_id());
		this.setStd_event(getStd_event());
		this.setDescription(getDescription());
		this.setAttachment(getAttachment());
		this.setRecipient_id(getRecipient_id());
		this.setRecipient_name(getRecipient_name());
		this.setMemoid(getMemoid());
		this.setStatus(getStatus());
		this.setRequested(getRequested());
		this.setRespn_date(getRespn_date());
		this.setSecond_request(getSecond_request());
		this.setApplication_formid(getApplication_formid());
		this.setFreeformind(getFreeformind());
		this.setStdletterTextArea(getStdletterTextArea());
	}


	public void validateForm(FormActionContext ctx)
	{

		
	}

	
}