/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.epm.acmi.struts.form;

import org.apache.struts.action.ActionForm;

/** 
 * MyEclipse Struts
 * Creation date: 04-15-2008
 * 
 * XDoclet definition:
 * @struts.form name="notesForm"
 */
public class NotesForm extends ActionForm {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
}