/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.epm.acmi.struts.form;

import org.apache.struts.action.ActionForm;

/** 
 * MyEclipse Struts
 * Creation date: 04-07-2008
 * 
 * XDoclet definition:
 * @struts.form name="personCompanyMainForm"
 */
public class PersonCompanyMainForm extends ActionForm {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private String personid;
	private String first_name;
	private String person_title;
	private String middle_name;
	private String honorifics;
	private String last_name;
	private String suffix;
	private String dependof;
	private String sex;
	private String birth_date;
	private String birth_place;
	private String disability;
	private String marital_status;
	private String height;
	private String weight;
	private String smoker;
	private String occupation;
	private String student;
	private String college;
	private String employer;
	private String length;
	private String month_income;
	private String business_phone;
	private String res_phone;
	private String social_sec;
	private String drivers_license;
	private String state;
	private String company_name;
	private String company_address;
	private String mib_terr;
	private String dependents;
	private String no_in_array;
	private String app_declined;
	
	public PersonCompanyMainForm() {
		super();
		// TODO Auto-generated constructor stub
	}

	public PersonCompanyMainForm(String personid, String first_name,
			String person_title, String middle_name, String honorifics,
			String last_name, String suffix, String dependof, String sex,
			String birth_date, String birth_place, String disability,
			String marital_status, String height, String weight, String smoker,
			String occupation, String student, String college, String employer,
			String length, String month_income, String business_phone,
			String res_phone, String social_sec, String drivers_license,
			String state, String company_name, String company_address,
			String mib_terr, String dependents, String no_in_array,
			String app_declined) {
		super();
		this.personid = personid;
		this.first_name = first_name;
		this.person_title = person_title;
		this.middle_name = middle_name;
		this.honorifics = honorifics;
		this.last_name = last_name;
		this.suffix = suffix;
		this.dependof = dependof;
		this.sex = sex;
		this.birth_date = birth_date;
		this.birth_place = birth_place;
		this.disability = disability;
		this.marital_status = marital_status;
		this.height = height;
		this.weight = weight;
		this.smoker = smoker;
		this.occupation = occupation;
		this.student = student;
		this.college = college;
		this.employer = employer;
		this.length = length;
		this.month_income = month_income;
		this.business_phone = business_phone;
		this.res_phone = res_phone;
		this.social_sec = social_sec;
		this.drivers_license = drivers_license;
		this.state = state;
		this.company_name = company_name;
		this.company_address = company_address;
		this.mib_terr = mib_terr;
		this.dependents = dependents;
		this.no_in_array = no_in_array;
		this.app_declined = app_declined;
	}

	public String getPersonid() {
		return personid;
	}

	public void setPersonid(String personid) {
		this.personid = personid;
	}

	public String getFirst_name() {
		return first_name;
	}

	public void setFirst_name(String first_name) {
		this.first_name = first_name;
	}

	public String getPerson_title() {
		return person_title;
	}

	public void setPerson_title(String person_title) {
		this.person_title = person_title;
	}

	public String getMiddle_name() {
		return middle_name;
	}

	public void setMiddle_name(String middle_name) {
		this.middle_name = middle_name;
	}

	public String getHonorifics() {
		return honorifics;
	}

	public void setHonorifics(String honorifics) {
		this.honorifics = honorifics;
	}

	public String getLast_name() {
		return last_name;
	}

	public void setLast_name(String last_name) {
		this.last_name = last_name;
	}

	public String getSuffix() {
		return suffix;
	}

	public void setSuffix(String suffix) {
		this.suffix = suffix;
	}

	public String getDependof() {
		return dependof;
	}

	public void setDependof(String dependof) {
		this.dependof = dependof;
	}

	public String getSex() {
		return sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	public String getBirth_date() {
		return birth_date;
	}

	public void setBirth_date(String birth_date) {
		this.birth_date = birth_date;
	}

	public String getBirth_place() {
		return birth_place;
	}

	public void setBirth_place(String birth_place) {
		this.birth_place = birth_place;
	}

	public String getDisability() {
		return disability;
	}

	public void setDisability(String disability) {
		this.disability = disability;
	}

	public String getMarital_status() {
		return marital_status;
	}

	public void setMarital_status(String marital_status) {
		this.marital_status = marital_status;
	}

	public String getHeight() {
		return height;
	}

	public void setHeight(String height) {
		this.height = height;
	}

	public String getWeight() {
		return weight;
	}

	public void setWeight(String weight) {
		this.weight = weight;
	}

	public String getSmoker() {
		return smoker;
	}

	public void setSmoker(String smoker) {
		this.smoker = smoker;
	}

	public String getOccupation() {
		return occupation;
	}

	public void setOccupation(String occupation) {
		this.occupation = occupation;
	}

	public String getStudent() {
		return student;
	}

	public void setStudent(String student) {
		this.student = student;
	}

	public String getCollege() {
		return college;
	}

	public void setCollege(String college) {
		this.college = college;
	}

	public String getEmployer() {
		return employer;
	}

	public void setEmployer(String employer) {
		this.employer = employer;
	}

	public String getLength() {
		return length;
	}

	public void setLength(String length) {
		this.length = length;
	}

	public String getMonth_income() {
		return month_income;
	}

	public void setMonth_income(String month_income) {
		this.month_income = month_income;
	}

	public String getBusiness_phone() {
		return business_phone;
	}

	public void setBusiness_phone(String business_phone) {
		this.business_phone = business_phone;
	}

	public String getRes_phone() {
		return res_phone;
	}

	public void setRes_phone(String res_phone) {
		this.res_phone = res_phone;
	}

	public String getSocial_sec() {
		return social_sec;
	}

	public void setSocial_sec(String social_sec) {
		this.social_sec = social_sec;
	}

	public String getDrivers_license() {
		return drivers_license;
	}

	public void setDrivers_license(String drivers_license) {
		this.drivers_license = drivers_license;
	}

	public String getState() {
		return state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public String getCompany_name() {
		return company_name;
	}

	public void setCompany_name(String company_name) {
		this.company_name = company_name;
	}

	public String getCompany_address() {
		return company_address;
	}

	public void setCompany_address(String company_address) {
		this.company_address = company_address;
	}

	public String getMib_terr() {
		return mib_terr;
	}

	public void setMib_terr(String mib_terr) {
		this.mib_terr = mib_terr;
	}

	public String getDependents() {
		return dependents;
	}

	public void setDependents(String dependents) {
		this.dependents = dependents;
	}

	public String getNo_in_array() {
		return no_in_array;
	}

	public void setNo_in_array(String no_in_array) {
		this.no_in_array = no_in_array;
	}

	public String getApp_declined() {
		return app_declined;
	}

	public void setApp_declined(String app_declined) {
		this.app_declined = app_declined;
	}
	
	
}