/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.epm.acmi.struts.form;

import java.util.TreeMap;

import org.apache.struts.action.ActionForm;

import com.cc.acmi.common.DiaryMessages;
import com.cc.acmi.presentation.dsp.ConditionCodeDsp;
import com.cc.framework.adapter.struts.FormActionContext;
import com.cc.framework.ui.control.SimpleListControl;
import com.epm.acmi.datamodel.ConditionCodesDisplayList;
import com.epm.acmi.util.ACMICache;

/** 
 * MyEclipse Struts
 * Creation date: 04-08-2008
 * 
 * XDoclet definition:
 * @struts.form name="subStdCoverageMainForm"
 */
public class PolicyConditionCodesMainForm extends ActionForm 
{
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private String USER_ID;

	private String POLICY_ID;

	private String PERSON_ID;


	private String CONDITION_CODEONE;

	private String CONDITION_CODETWO;

	private String CONDITION_CODETHREE;

	private String CONDITION_CODEFOUR;

	private String CONDITION_TEXTONE;

	private String CONDITION_TEXTTWO;

	private String CONDITION_TEXTTHREE;

	private String CONDITION_TEXTFOUR;

	private String POLICY_STATUS;

	private String PERSON_STATUS_IND;

	private String STATUS_EFF_DATE;

	private String PERSON_STATUS_EFF_DATE;

	private String PERSON_NAME;

	private String NEXT_DUE_DATE;

	private String DISPLAY_DATE;

	private String REQ_EFF_DATE;
	
	private String CCODE_START_DATE;
	
	private String CCODE_TERM_DATE;
	
	private String CCODE_TIME_PERIOD;
	
	private String STATE_ISSUED;
		
	private String currentPosition;
	
	private String log_counter = "";
	
	public TreeMap getCondictionCodesOptions()
	{
		
//		TreeMap status = new TreeMap();
			
        
//		 ALC/DRUG  ALCOHOL AND/OR DRUG   
//		 ALLG      ALLERGIES             
//		 ANEM      ANEMIA                
//		 APNEA     SLEEP APNEA           
//		 ARTH      ARTHRITIS             
//		 AST/ALLG  ASTHMA AND ALLERGIES  
//		 ASTH      ASTHMA     
		
//		status.put("ALC/DRUG", "ALC/DRUG: ALCOHOL AND/OR DRUG");
//		status.put("ALLG", "ALLG: ALLERGIES");
//		status.put("ANEM", "ANEM: ANEMIA");
//		status.put("APNEA", "APNEA: SLEEP APNEA");
//		status.put("ARTH", "ARTH: ARTHRITIS");
//		status.put("AST/ALLG", "AST/ALLG: ASTHMA AND ALLERGIES");
//		status.put("ASTH", "ASTH: ASTHMA");
		
		return ACMICache.getConditionCodes();
		
	}	
	

	public String getUSER_ID() {
		return USER_ID;
	}




	public void setUSER_ID(String user_id) {
		USER_ID = user_id;
	}




	public String getPOLICY_ID() {
		return POLICY_ID;
	}




	public void setPOLICY_ID(String policy_id) {
		POLICY_ID = policy_id;
	}




	public String getPERSON_ID() {
		return PERSON_ID;
	}




	public void setPERSON_ID(String person_id) {
		PERSON_ID = person_id;
	}


	public String getCONDITION_CODEONE() {
		return CONDITION_CODEONE;
	}




	public void setCONDITION_CODEONE(String condition_codeone) {
		CONDITION_CODEONE = condition_codeone;
	}




	public String getCONDITION_CODETWO() {
		return CONDITION_CODETWO;
	}




	public void setCONDITION_CODETWO(String condition_codetwo) {
		CONDITION_CODETWO = condition_codetwo;
	}




	public String getCONDITION_CODETHREE() {
		return CONDITION_CODETHREE;
	}




	public void setCONDITION_CODETHREE(String condition_codethree) {
		CONDITION_CODETHREE = condition_codethree;
	}




	public String getCONDITION_CODEFOUR() {
		return CONDITION_CODEFOUR;
	}




	public void setCONDITION_CODEFOUR(String condition_codefour) {
		CONDITION_CODEFOUR = condition_codefour;
	}




	public String getCONDITION_TEXTONE() {
		return CONDITION_TEXTONE;
	}




	public void setCONDITION_TEXTONE(String condition_textone) {
		CONDITION_TEXTONE = condition_textone;
	}




	public String getCONDITION_TEXTTWO() {
		return CONDITION_TEXTTWO;
	}




	public void setCONDITION_TEXTTWO(String condition_texttwo) {
		CONDITION_TEXTTWO = condition_texttwo;
	}




	public String getCONDITION_TEXTTHREE() {
		return CONDITION_TEXTTHREE;
	}




	public void setCONDITION_TEXTTHREE(String condition_textthree) {
		CONDITION_TEXTTHREE = condition_textthree;
	}




	public String getCONDITION_TEXTFOUR() {
		return CONDITION_TEXTFOUR;
	}




	public void setCONDITION_TEXTFOUR(String condition_textfour) {
		CONDITION_TEXTFOUR = condition_textfour;
	}


	public String getPOLICY_STATUS() {
		return POLICY_STATUS;
	}




	public void setPOLICY_STATUS(String policy_status) {
		POLICY_STATUS = policy_status;
	}




	public String getPERSON_STATUS_IND() {
		return PERSON_STATUS_IND;
	}




	public void setPERSON_STATUS_IND(String person_status_ind) {
		PERSON_STATUS_IND = person_status_ind;
	}




	public String getSTATUS_EFF_DATE() {
		return STATUS_EFF_DATE;
	}




	public void setSTATUS_EFF_DATE(String status_eff_date) {
		STATUS_EFF_DATE = status_eff_date;
	}




	public String getPERSON_STATUS_EFF_DATE() {
		return PERSON_STATUS_EFF_DATE;
	}




	public void setPERSON_STATUS_EFF_DATE(String person_status_eff_date) {
		PERSON_STATUS_EFF_DATE = person_status_eff_date;
	}




	public String getPERSON_NAME() {
		return PERSON_NAME;
	}




	public void setPERSON_NAME(String person_name) {
		PERSON_NAME = person_name;
	}




	public String getNEXT_DUE_DATE() {
		return NEXT_DUE_DATE;
	}




	public void setNEXT_DUE_DATE(String next_due_date) {
		NEXT_DUE_DATE = next_due_date;
	}




	public String getDISPLAY_DATE() {
		return DISPLAY_DATE;
	}




	public void setDISPLAY_DATE(String display_date) {
		DISPLAY_DATE = display_date;
	}


	public String getREQ_EFF_DATE() {
		return REQ_EFF_DATE;
	}




	public void setREQ_EFF_DATE(String req_eff_date) {
		REQ_EFF_DATE = req_eff_date;
	}


	public String getCCODE_START_DATE() {
		return CCODE_START_DATE;
	}


	public void setCCODE_START_DATE(String ccode_start_date) {
		CCODE_START_DATE = ccode_start_date;
	}


	public String getCCODE_TERM_DATE() {
		return CCODE_TERM_DATE;
	}


	public void setCCODE_TERM_DATE(String ccode_term_date) {
		CCODE_TERM_DATE = ccode_term_date;
	}


	public String getCCODE_TIME_PERIOD() {
		return CCODE_TIME_PERIOD;
	}


	public void setCCODE_TIME_PERIOD(String ccode_time_period) {
		CCODE_TIME_PERIOD = ccode_time_period;
	}


	public String getSTATE_ISSUED() {
		return STATE_ISSUED;
	}


	public void setSTATE_ISSUED(String state_issued) {
		STATE_ISSUED = state_issued;
	}


	public void clear()
	{
	
		setUSER_ID("");
	
		setPOLICY_ID("");
	
		setPERSON_ID("");
	
	
		setCONDITION_CODEONE("");
	
		setCONDITION_CODETWO("");
	
		setCONDITION_CODETHREE("");
	
		setCONDITION_CODEFOUR("");
	
		setCONDITION_TEXTONE("");
	
		setCONDITION_TEXTTWO("");
	
		setCONDITION_TEXTTHREE("");
	
		setCONDITION_TEXTFOUR("");
	
	
		setPOLICY_STATUS("");
	
		setPERSON_STATUS_IND("");
	
		setSTATUS_EFF_DATE("");
	
		setPERSON_STATUS_EFF_DATE("");
	
		setPERSON_NAME("");
	
		setNEXT_DUE_DATE("");
	
		setDISPLAY_DATE("");
	
		setREQ_EFF_DATE("");
		
		setCCODE_START_DATE("");
		
		setCCODE_TERM_DATE("");
	
		setCCODE_TIME_PERIOD("");
		
		setSTATE_ISSUED("");
		
		setLog_counter("");
	
	}

	
	public void save() 
	{
		setUSER_ID(getUSER_ID());
		
		setPOLICY_ID(getPOLICY_ID());
	
		setPERSON_ID(getPERSON_ID());
		
		setCONDITION_CODEONE(getCONDITION_CODEONE());
	
		setCONDITION_CODETWO(getCONDITION_CODETWO());
	
		setCONDITION_CODETHREE(getCONDITION_CODETHREE());
	
		setCONDITION_CODEFOUR(getCONDITION_CODEFOUR());
	
		setCONDITION_TEXTONE(getCONDITION_TEXTONE());
	
		setCONDITION_TEXTTWO(getCONDITION_TEXTTWO());
	
		setCONDITION_TEXTTHREE(getCONDITION_TEXTTHREE());
	
		setCONDITION_TEXTFOUR(getCONDITION_TEXTFOUR());
	
		setPOLICY_STATUS(getPOLICY_STATUS());
	
		setPERSON_STATUS_IND(getPERSON_STATUS_IND());
	
		setSTATUS_EFF_DATE(getSTATUS_EFF_DATE());
	
		setPERSON_STATUS_EFF_DATE(getPERSON_STATUS_EFF_DATE());
	
		setPERSON_NAME(getPERSON_NAME());
	
		setNEXT_DUE_DATE(getNEXT_DUE_DATE());
	
		setDISPLAY_DATE(getDISPLAY_DATE());
	
		setREQ_EFF_DATE(getREQ_EFF_DATE());
		
		setCCODE_START_DATE(getCCODE_START_DATE());
		
		setCCODE_TERM_DATE(getCCODE_TERM_DATE());
	
		setCCODE_TIME_PERIOD(getCCODE_TIME_PERIOD());
		
		setSTATE_ISSUED(getSTATE_ISSUED());
	
		setLog_counter(getLog_counter());
	
	}


	public void validateForm(FormActionContext ctx) 
	{
		validateConditionCodeList(ctx);	
	}

	public void validateConditionCodeList(FormActionContext ctx)
	{
		SimpleListControl conditionCodeList = (SimpleListControl) ctx.session().getAttribute("conditionCodeList");
		ConditionCodesDisplayList ConditionDspData = (ConditionCodesDisplayList)conditionCodeList.getDataModel();
		ConditionCodeDsp[] conditionCodeData = ConditionDspData.getData();
		
		int position = 0;
		
		for(int c = 0; c < conditionCodeData.length; c++)
		{
			if(conditionCodeData[c].getDESCRIPTION().trim().length() == 0)
			{
				if (conditionCodeData[c].getCODE().trim().length() != 0 )
				{	
					position  = c + 1;
					ctx.addGlobalError(DiaryMessages.ERROR_CONDITION_DESCRIPTION_TEXT, conditionCodeData[c].getCODE(), Integer.toString(position));
				}
				
			}
		}
		
		
	}

	public String getCurrentPosition() {
		return currentPosition;
	}


	public void setCurrentPosition(String currentPosition) {
		this.currentPosition = currentPosition;
	}


	public String getLog_counter() {
		return log_counter;
	}


	public void setLog_counter(String log_counter) {
		this.log_counter = log_counter;
	}

}