/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.epm.acmi.struts.form;

import org.apache.struts.action.ActionForm;

import com.cc.framework.adapter.struts.FormActionContext;

/** 
 * MyEclipse Struts
 * Creation date: 04-03-2008
 * 
 * XDoclet definition:
 * @struts.form name="policyExtendedCommentsMainMainForm"
 */
public class PolicyExtendedCommentsMainForm extends ActionForm {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private String policy_id = "";
	private String description = "";
	private String freeTextArea = "";
	private String autoSave ="";
	
	
	public PolicyExtendedCommentsMainForm(String policy_id, String description,
			String freeTextArea) {
		super();
		this.policy_id = policy_id;
		this.description = description;
		this.freeTextArea = freeTextArea;
	}


	public String getPolicy_id() {
		return policy_id;
	}


	public void setPolicy_id(String policy_id) {
		this.policy_id = policy_id;
	}


	public String getDescription() {
		return description;
	}


	public void setDescription(String description) {
		this.description = description;
	}


	public String getFreeTextArea() {
		return freeTextArea;
	}


	public void setFreeTextArea(String freeTextArea) {
		this.freeTextArea = freeTextArea;
	}


	public PolicyExtendedCommentsMainForm() {
		super();
		// TODO Auto-generated constructor stub
	}
	
	
	public void clear()
	{
		this.setPolicy_id("");
		this.setDescription("");
		this.setFreeTextArea("");
		this.setAutoSave("");
	}
	
	public void save()
	{
		this.setPolicy_id(getPolicy_id());
		this.setDescription(getDescription());
		this.setFreeTextArea(getFreeTextArea());
		this.setAutoSave("false");
	}
	
	public void validateForm(FormActionContext ctx) {
		// TODO Auto-generated method stub
		
	}


	public String getAutoSave() {
		return autoSave;
	}


	public void setAutoSave(String autoSave) {
		this.autoSave = autoSave;
	}
	
}