/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.epm.acmi.struts.form;

import java.util.TreeMap;

import org.apache.struts.action.ActionForm;

import com.cc.acmi.common.FieldCheckCustom;
import com.cc.framework.adapter.struts.FormActionContext;

/** 
 * MyEclipse Struts
 * Creation date: 04-08-2008
 * 
 * XDoclet definition:
 * @struts.form name="riderMainForm"
 */
public class RiderMainForm extends ActionForm {
	
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private String PERSON_ID="";
	private String POLICY_ID="";
	private String INSURED_SEARCH_NAME="";
	private String KEY_INSURED_SEARCH_NAME="";
	private String RIDER_FLAG="";
	private String PRODUCT_CODE="";
	private String STATE="";

	private String RIDER_CODE_ONE="";
	private String RIDER_DESCRIPTION_ONE="";
	private String RID_TIME_PERIOD_ONE="";
	private String RIDER_START_DATE_ONE="";
	private String RIDER_END_DATE_ONE="";
	private String RIDER_TEXT_ONE="";
	
	private String RIDER_CODE_TWO="";
	private String RIDER_DESCRIPTION_TWO="";
	private String RID_TIME_PERIOD_TWO="";
	private String RIDER_START_DATE_TWO="";
	private String RIDER_END_DATE_TWO="";
	private String RIDER_TEXT_TWO="";
	
	private String RIDER_CODE_THREE="";
	private String RIDER_DESCRIPTION_THREE="";
	private String RID_TIME_PERIOD_THREE="";
	private String RIDER_START_DATE_THREE="";
	private String RIDER_END_DATE_THREE="";
	private String RIDER_TEXT_THREE="";
	
	private String RIDER_CODE_FOUR="";
	private String RIDER_DESCRIPTION_FOUR="";
	private String RID_TIME_PERIOD_FOUR="";
	private String RIDER_START_DATE_FOUR="";
	private String RIDER_END_DATE_FOUR="";
	private String RIDER_TEXT_FOUR="";
	
	private String RIDER_CODE_FIVE="";
	private String RIDER_DESCRIPTION_FIVE="";
	private String RID_TIME_PERIOD_FIVE="";
	private String RIDER_START_DATE_FIVE="";
	private String RIDER_END_DATE_FIVE="";
	private String RIDER_TEXT_FIVE="";
	
	public TreeMap getRestrictedOptions()
	{
		
		TreeMap status = new TreeMap();
		
		status.put(" ", " ");
		status.put("Y", "Yes");
		status.put("N", "No");
		
		return status;
	}
	
	
	public String getPERSON_ID() {
		return PERSON_ID;
	}
	public void setPERSON_ID(String person_id) {
		PERSON_ID = person_id;
	}
	public String getPOLICY_ID() {
		return POLICY_ID;
	}
	public void setPOLICY_ID(String policy_id) {
		POLICY_ID = policy_id;
	}
	public String getINSURED_SEARCH_NAME() {
		return INSURED_SEARCH_NAME;
	}
	public void setINSURED_SEARCH_NAME(String insured_search_name) {
		INSURED_SEARCH_NAME = insured_search_name;
	}
	public String getKEY_INSURED_SEARCH_NAME() {
		return KEY_INSURED_SEARCH_NAME;
	}
	public void setKEY_INSURED_SEARCH_NAME(String key_insured_search_name) {
		KEY_INSURED_SEARCH_NAME = key_insured_search_name;
	}
	public String getRIDER_FLAG() {
		return RIDER_FLAG;
	}
	public void setRIDER_FLAG(String rider_flag) {
		RIDER_FLAG = rider_flag;
	}
	public String getRIDER_CODE_ONE() {
		return RIDER_CODE_ONE;
	}
	public void setRIDER_CODE_ONE(String rider_code_one) {
		RIDER_CODE_ONE = rider_code_one;
	}
	public String getRIDER_DESCRIPTION_ONE() {
		return RIDER_DESCRIPTION_ONE;
	}
	public void setRIDER_DESCRIPTION_ONE(String rider_description_one) {
		RIDER_DESCRIPTION_ONE = rider_description_one;
	}
	public String getRID_TIME_PERIOD_ONE() {
		return RID_TIME_PERIOD_ONE;
	}
	public void setRID_TIME_PERIOD_ONE(String rid_time_period_one) {
		RID_TIME_PERIOD_ONE = rid_time_period_one;
	}
	public String getRIDER_START_DATE_ONE() {
		return RIDER_START_DATE_ONE;
	}
	public void setRIDER_START_DATE_ONE(String rider_start_date_one) {
		RIDER_START_DATE_ONE = rider_start_date_one;
	}
	public String getRIDER_END_DATE_ONE() {
		return RIDER_END_DATE_ONE;
	}
	public void setRIDER_END_DATE_ONE(String rider_end_date_one) {
		RIDER_END_DATE_ONE = rider_end_date_one;
	}
	public String getRIDER_TEXT_ONE() {
		return RIDER_TEXT_ONE;
	}
	public void setRIDER_TEXT_ONE(String rider_text_one) {
		RIDER_TEXT_ONE = rider_text_one;
	}
	public String getRIDER_CODE_TWO() {
		return RIDER_CODE_TWO;
	}
	public void setRIDER_CODE_TWO(String rider_code_two) {
		RIDER_CODE_TWO = rider_code_two;
	}
	public String getRIDER_DESCRIPTION_TWO() {
		return RIDER_DESCRIPTION_TWO;
	}
	public void setRIDER_DESCRIPTION_TWO(String rider_description_two) {
		RIDER_DESCRIPTION_TWO = rider_description_two;
	}
	public String getRID_TIME_PERIOD_TWO() {
		return RID_TIME_PERIOD_TWO;
	}
	public void setRID_TIME_PERIOD_TWO(String rid_time_period_two) {
		RID_TIME_PERIOD_TWO = rid_time_period_two;
	}
	public String getRIDER_START_DATE_TWO() {
		return RIDER_START_DATE_TWO;
	}
	public void setRIDER_START_DATE_TWO(String rider_start_date_two) {
		RIDER_START_DATE_TWO = rider_start_date_two;
	}
	public String getRIDER_END_DATE_TWO() {
		return RIDER_END_DATE_TWO;
	}
	public void setRIDER_END_DATE_TWO(String rider_end_date_two) {
		RIDER_END_DATE_TWO = rider_end_date_two;
	}
	public String getRIDER_TEXT_TWO() {
		return RIDER_TEXT_TWO;
	}
	public void setRIDER_TEXT_TWO(String rider_text_two) {
		RIDER_TEXT_TWO = rider_text_two;
	}
	public String getRIDER_CODE_THREE() {
		return RIDER_CODE_THREE;
	}
	public void setRIDER_CODE_THREE(String rider_code_three) {
		RIDER_CODE_THREE = rider_code_three;
	}
	public String getRIDER_DESCRIPTION_THREE() {
		return RIDER_DESCRIPTION_THREE;
	}
	public void setRIDER_DESCRIPTION_THREE(String rider_description_three) {
		RIDER_DESCRIPTION_THREE = rider_description_three;
	}
	public String getRID_TIME_PERIOD_THREE() {
		return RID_TIME_PERIOD_THREE;
	}
	public void setRID_TIME_PERIOD_THREE(String rid_time_period_three) {
		RID_TIME_PERIOD_THREE = rid_time_period_three;
	}
	public String getRIDER_START_DATE_THREE() {
		return RIDER_START_DATE_THREE;
	}
	public void setRIDER_START_DATE_THREE(String rider_start_date_three) {
		RIDER_START_DATE_THREE = rider_start_date_three;
	}
	public String getRIDER_END_DATE_THREE() {
		return RIDER_END_DATE_THREE;
	}
	public void setRIDER_END_DATE_THREE(String rider_end_date_three) {
		RIDER_END_DATE_THREE = rider_end_date_three;
	}
	public String getRIDER_TEXT_THREE() {
		return RIDER_TEXT_THREE;
	}
	public void setRIDER_TEXT_THREE(String rider_text_three) {
		RIDER_TEXT_THREE = rider_text_three;
	}
	public String getRIDER_CODE_FOUR() {
		return RIDER_CODE_FOUR;
	}
	public void setRIDER_CODE_FOUR(String rider_code_four) {
		RIDER_CODE_FOUR = rider_code_four;
	}
	public String getRIDER_DESCRIPTION_FOUR() {
		return RIDER_DESCRIPTION_FOUR;
	}
	public void setRIDER_DESCRIPTION_FOUR(String rider_description_four) {
		RIDER_DESCRIPTION_FOUR = rider_description_four;
	}
	public String getRID_TIME_PERIOD_FOUR() {
		return RID_TIME_PERIOD_FOUR;
	}
	public void setRID_TIME_PERIOD_FOUR(String rid_time_period_four) {
		RID_TIME_PERIOD_FOUR = rid_time_period_four;
	}
	public String getRIDER_START_DATE_FOUR() {
		return RIDER_START_DATE_FOUR;
	}
	public void setRIDER_START_DATE_FOUR(String rider_start_date_four) {
		RIDER_START_DATE_FOUR = rider_start_date_four;
	}
	public String getRIDER_END_DATE_FOUR() {
		return RIDER_END_DATE_FOUR;
	}
	public void setRIDER_END_DATE_FOUR(String rider_end_date_four) {
		RIDER_END_DATE_FOUR = rider_end_date_four;
	}
	public String getRIDER_TEXT_FOUR() {
		return RIDER_TEXT_FOUR;
	}
	public void setRIDER_TEXT_FOUR(String rider_text_four) {
		RIDER_TEXT_FOUR = rider_text_four;
	}
	public String getRIDER_CODE_FIVE() {
		return RIDER_CODE_FIVE;
	}
	public void setRIDER_CODE_FIVE(String rider_code_five) {
		RIDER_CODE_FIVE = rider_code_five;
	}
	public String getRIDER_DESCRIPTION_FIVE() {
		return RIDER_DESCRIPTION_FIVE;
	}
	public void setRIDER_DESCRIPTION_FIVE(String rider_description_five) {
		RIDER_DESCRIPTION_FIVE = rider_description_five;
	}
	public String getRID_TIME_PERIOD_FIVE() {
		return RID_TIME_PERIOD_FIVE;
	}
	public void setRID_TIME_PERIOD_FIVE(String rid_time_period_five) {
		RID_TIME_PERIOD_FIVE = rid_time_period_five;
	}
	public String getRIDER_START_DATE_FIVE() {
		return RIDER_START_DATE_FIVE;
	}
	public void setRIDER_START_DATE_FIVE(String rider_start_date_five) {
		RIDER_START_DATE_FIVE = rider_start_date_five;
	}
	public String getRIDER_END_DATE_FIVE() {
		return RIDER_END_DATE_FIVE;
	}
	public void setRIDER_END_DATE_FIVE(String rider_end_date_five) {
		RIDER_END_DATE_FIVE = rider_end_date_five;
	}
	public String getRIDER_TEXT_FIVE() {
		return RIDER_TEXT_FIVE;
	}
	public void setRIDER_TEXT_FIVE(String rider_text_five) {
		RIDER_TEXT_FIVE = rider_text_five;
	}
	
	public String getPRODUCT_CODE() {
		return PRODUCT_CODE;
	}
	public void setPRODUCT_CODE(String product_code) {
		PRODUCT_CODE = product_code;
	}

	public String getSTATE() {
		return STATE;
	}


	public void setSTATE(String state) {
		STATE = state;
	}
	

	public void validateForm(FormActionContext ctx) 
	{
		FieldCheckCustom.validateTextBox(this.getRIDER_TEXT_ONE(), ctx, "RIDER_TEXT_ONE", "250");
		FieldCheckCustom.validateTextBoxLineLimit(this.getRIDER_TEXT_ONE(), ctx, "RIDER_TEXT_ONE", "5", 50,5 );
		FieldCheckCustom.validateTextBox(this.getRIDER_TEXT_TWO(), ctx, "RIDER_TEXT_TWO", "250");
		FieldCheckCustom.validateTextBoxLineLimit(this.getRIDER_TEXT_TWO(), ctx, "RIDER_TEXT_TWO", "5", 50,5);
		FieldCheckCustom.validateTextBox(this.getRIDER_TEXT_THREE(), ctx, "RIDER_TEXT_THREE", "250");
		FieldCheckCustom.validateTextBoxLineLimit(this.getRIDER_TEXT_THREE(), ctx, "RIDER_TEXT_THREE", "5",50, 5);
		FieldCheckCustom.validateTextBox(this.getRIDER_TEXT_FOUR(), ctx, "RIDER_TEXT_FOUR", "250");
		FieldCheckCustom.validateTextBoxLineLimit(this.getRIDER_TEXT_FOUR(), ctx, "RIDER_TEXT_FOUR", "5",50, 5);
		FieldCheckCustom.validateTextBox(this.getRIDER_TEXT_FIVE(), ctx, "RIDER_TEXT_FIVE", "250");
		FieldCheckCustom.validateTextBoxLineLimit(this.getRIDER_TEXT_FIVE(), ctx, "RIDER_TEXT_FIVE", "5", 50, 5);
	}



	public void clear()
	{
		setPERSON_ID("");
		setPOLICY_ID("");
		setINSURED_SEARCH_NAME("");
		setKEY_INSURED_SEARCH_NAME("");
		setRIDER_FLAG("");
		setPRODUCT_CODE("");
		setRIDER_CODE_ONE("");
		setRIDER_DESCRIPTION_ONE("");
		setRID_TIME_PERIOD_ONE("");
		setRIDER_START_DATE_ONE("");
		setRIDER_END_DATE_ONE("");
		setRIDER_TEXT_ONE("");
		setRIDER_CODE_TWO("");
		setRIDER_DESCRIPTION_TWO("");
		setRID_TIME_PERIOD_TWO("");
		setRIDER_START_DATE_TWO("");
		setRIDER_END_DATE_TWO("");
		setRIDER_TEXT_TWO("");
		setRIDER_CODE_THREE("");
		setRIDER_DESCRIPTION_THREE("");
		setRID_TIME_PERIOD_THREE("");
		setRIDER_START_DATE_THREE("");
		setRIDER_END_DATE_THREE("");
		setRIDER_TEXT_THREE("");
		setRIDER_CODE_FOUR("");
		setRIDER_DESCRIPTION_FOUR("");
		setRID_TIME_PERIOD_FOUR("");
		setRIDER_START_DATE_FOUR("");
		setRIDER_END_DATE_FOUR("");
		setRIDER_TEXT_FOUR("");
		setRIDER_CODE_FIVE("");
		setRIDER_DESCRIPTION_FIVE("");
		setRID_TIME_PERIOD_FIVE("");
		setRIDER_START_DATE_FIVE("");
		setRIDER_END_DATE_FIVE("");
		setRIDER_TEXT_FIVE("");
		setSTATE("");
	}
	
	public void save()
	{
		setPERSON_ID(getPERSON_ID());
		setPOLICY_ID(getPOLICY_ID());
		setINSURED_SEARCH_NAME(getINSURED_SEARCH_NAME());
		setKEY_INSURED_SEARCH_NAME(getKEY_INSURED_SEARCH_NAME());
		setRIDER_FLAG(getRIDER_FLAG());
		setPRODUCT_CODE(getPRODUCT_CODE());
		
		setRIDER_CODE_ONE(getRIDER_CODE_ONE());
		setRIDER_DESCRIPTION_ONE(getRIDER_DESCRIPTION_ONE());
		setRID_TIME_PERIOD_ONE(getRID_TIME_PERIOD_ONE());
		setRIDER_START_DATE_ONE(getRIDER_START_DATE_ONE());
		setRIDER_END_DATE_ONE(getRIDER_END_DATE_ONE());
		setRIDER_TEXT_ONE(getRIDER_TEXT_ONE());
	
		setRIDER_CODE_TWO(getRIDER_CODE_TWO());
		setRIDER_DESCRIPTION_TWO(getRIDER_DESCRIPTION_TWO());
		setRID_TIME_PERIOD_TWO(getRID_TIME_PERIOD_TWO());
		setRIDER_START_DATE_TWO(getRIDER_START_DATE_TWO());
		setRIDER_END_DATE_TWO(getRIDER_END_DATE_TWO());
		setRIDER_TEXT_TWO(getRIDER_TEXT_TWO());
		
		setRIDER_CODE_THREE(getRIDER_CODE_THREE());
		setRIDER_DESCRIPTION_THREE(getRIDER_DESCRIPTION_THREE());
		setRID_TIME_PERIOD_THREE(getRID_TIME_PERIOD_THREE());
		setRIDER_START_DATE_THREE(getRIDER_START_DATE_THREE());
		setRIDER_END_DATE_THREE(getRIDER_END_DATE_THREE());
		setRIDER_TEXT_THREE(getRIDER_TEXT_THREE());
		
		setRIDER_CODE_FOUR(getRIDER_CODE_FOUR());
		setRIDER_DESCRIPTION_FOUR(getRIDER_DESCRIPTION_FOUR());
		setRID_TIME_PERIOD_FOUR(getRID_TIME_PERIOD_FOUR());
		setRIDER_START_DATE_FOUR(getRIDER_START_DATE_FOUR());
		setRIDER_END_DATE_FOUR(getRIDER_END_DATE_FOUR());
		setRIDER_TEXT_FOUR(getRIDER_TEXT_FOUR());
		
		setRIDER_CODE_FIVE(getRIDER_CODE_FIVE());
		setRIDER_DESCRIPTION_FIVE(getRIDER_DESCRIPTION_FIVE());
		setRID_TIME_PERIOD_FIVE(getRID_TIME_PERIOD_FIVE());
		setRIDER_START_DATE_FIVE(getRIDER_START_DATE_FIVE());
		setRIDER_END_DATE_FIVE(getRIDER_END_DATE_FIVE());
		setRIDER_TEXT_FIVE(getRIDER_TEXT_FIVE());
	
		setSTATE(getSTATE());
	}


	
	
}