/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.epm.acmi.struts.action;

import com.cc.framework.adapter.struts.ActionContext;

/** 
 * MyEclipse Struts
 * Creation date: 04-15-2008
 * 
 * XDoclet definition:
 * @struts.action path="/notes" name="notesForm" input="/jsp/ias/NotesMain.jsp" scope="request" validate="true"
 * @struts.action-forward name="back" path="/iuauser/iasdiary" redirect="true"
 */
public class NotesAction extends CCAction {

	public void doExecute(ActionContext arg0) throws Exception {
		// TODO Auto-generated method stub
		
	}
}