/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.epm.acmi.struts.action;

import org.apache.log4j.Logger;

import com.cc.acmi.common.Forwards;
import com.cc.framework.adapter.struts.ActionContext;
import com.cc.framework.adapter.struts.FormActionContext;
import com.epm.acmi.util.MiscellaneousUtils;

/** 
 * MyEclipse Struts
 * Creation date: 04-07-2008
 * 
 * XDoclet definition:
 * @struts.action path="/iuauser/personCompanyMain" name="personCompanyMainForm" input="/jsp/ias/PersonCompanyMainMain.jsp" scope="request" validate="true"
 * @struts.action-forward name="back" path="/iuauser/iasdiary.do" redirect="true"
 */
public class PersonCompanyMainAction extends CCAction {

	private static Logger log = MiscellaneousUtils.getIASLogger();
	
	public void doExecute(ActionContext ctx) throws Exception {
		log.debug("Begin execute doExecute");
		
		ctx.forwardToInput();
		log.debug("End execute doExecute");
		
	}
	
	/**
	 * This method is called if the back button is clicked
	 * @param ctx The FormActionContext
	 */
	public void back_onClick(FormActionContext ctx) throws Exception {
		// in this example we go back to the jsp
		ctx.forwardByName(Forwards.BACK);
	}
	
	/**
	 * This method is called if the save button is clicked
	 * @param ctx The FormActionContext
	 */
	public void save_onClick(FormActionContext ctx) throws Exception {
		// in this example we go back to the jsp
		ctx.forwardByName(Forwards.BACK);
	}
}